# This workflow defines the Continuous Integration (CI) process for the Projection Service.
# It automatically builds and pushes a Docker image to Docker Hub when a pull request is merged to the main branch.

name: CI - Build and Push Docker Image

# Trigger the workflow on a push event to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 for the Maven build
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the application with Maven
      # This creates the executable JAR file in the 'target' directory.
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Log in to Docker Hub
      # This uses the encrypted secrets you stored in your GitHub repository settings.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the Dockerfile in the root of the repository
          push: true   # Actually push the image to the registry
          # Replace 'your-dockerhub-username' with your actual Docker Hub username
          tags: your-dockerhub-username/projection-service:latest
