name: CI - Build and Push Docker Image

# Trigger the workflow on a push event to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      # This uses the encrypted secrets you stored in your GitHub repository settings.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the Dockerfile in the root of the repository
          push: true   # Actually push the image to the registry
          # Replace 'your-dockerhub-username' with your actual Docker Hub username
          tags: your-dockerhub-username/projection-service:latest
